// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "526b9bce-c59c-4a2f-9d4e-a99cc0703890",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Entities.Models.AlbumCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AlbumCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Karayolları Mah. 559 Sk. No:18/1 G.O.PAŞA / İSTANBUL / TÜRKİYE",
                            ContactPersonEmail = "cizgialbum@gmail.com",
                            ContactPersonName = "Test",
                            ContactPersonPhone = "+905359750193",
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3510),
                            Email = "cizgialbum@gmail.com",
                            Name = "ÇİZGİ ALBÜM FOTOĞRAFÇILIK",
                            Phone = "+02125387994",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Entities.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ActivationCode = new Guid("00000000-0000-0000-0000-000000000000"),
                            ConcurrencyStamp = "2494aab1-f536-475e-a804-2924eacae883",
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3366),
                            Email = "fotoeylul@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FOTOEYLUL@EMAIL.COM",
                            NormalizedUserName = "FOTOEYLUL",
                            PasswordHash = "AQAAAAIAAYagAAAAEFMVtCso8NL189pDOKyArskaHMQXXVN8CNrbsspozT0doJ6sqVnt5jSY+eWn2tLrhw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d8be4fb8-3fdd-4aab-b728-0639a9a10809",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "fotoeylul"
                        });
                });

            modelBuilder.Entity("Project.Entities.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrideName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Project.Entities.Models.ExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtraServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtraServiceCategoryId");

                    b.ToTable("ExtraServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            ExtraServiceCategoryId = 1,
                            ModifiedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            Name = "30x40 Kanvas",
                            Price = 600.00m,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            ExtraServiceCategoryId = 1,
                            ModifiedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            Name = "50x60 Kanvas",
                            Price = 950.00m,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            ExtraServiceCategoryId = 1,
                            Name = "50x70 Kanvas",
                            Price = 950.00m,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            ExtraServiceCategoryId = 1,
                            ModifiedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            Name = "70x100 Kanvas",
                            Price = 1200.00m,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            ExtraServiceCategoryId = 1,
                            Name = "75x100 3 Parçalı Kanvas",
                            Price = 2200.00m,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3748),
                            ExtraServiceCategoryId = 1,
                            Name = "75x125 5 Parçalı Kanvas",
                            Price = 3200.00m,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Entities.Models.ExtraServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExtraServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3651),
                            Name = "Kanvas",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3651),
                            Name = "Poster",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3651),
                            Name = "Saat",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3651),
                            Name = "Lüx Çerçeve",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3651),
                            Name = "Lake Çerçeve",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3651),
                            Name = "Oval Çerçeve",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Entities.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Yan Yol, Ataşehir, Rıfat Danışman Sok., 34758",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3565),
                            District = "Ataşehir",
                            IsFree = true,
                            Name = "Nezahat Gökyiğit Botanik Bahçesi",
                            Phone = "02164564437",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Küçük Çamlıca, 34696",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3565),
                            District = "Üsküdar",
                            IsFree = true,
                            Name = "Küçük Çamlıca",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kandilli, Vaniköy Cd No : 12, 34684",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3565),
                            District = "Üsküdar",
                            IsFree = true,
                            Name = "Adile Sultan Kasrı",
                            Phone = "(0216) 332 23 33",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Yıldız, Çırağan Cd., 34349",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3565),
                            District = "Beşiktaş",
                            IsFree = true,
                            Name = "Yıldız Parkı",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "Piri Paşa, Rahmi M. Koç Caddesi No: 3, 34445",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3565),
                            District = "Beyoğlu",
                            IsFree = false,
                            Name = "Rahmi M. Koç Müzesi",
                            Phone = "(0212) 369 66 00",
                            Price = 600.00m,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "Reşitpaşa, Emirgan Sk., 34467",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3565),
                            District = "Sarıyer",
                            IsFree = true,
                            Name = "Emirgan Korusu",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Entities.Models.PackageOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PackageOptions");
                });

            modelBuilder.Entity("Project.Entities.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("money");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Project.Entities.Models.Photographer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasColumnType("money");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Photographers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3531),
                            Fee = 2000.00m,
                            FirstName = "Hakan",
                            LastName = "Akınsu",
                            ModifiedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3531),
                            Phone = "05538971905",
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3531),
                            Fee = 5000.00m,
                            FirstName = "Mustafa Osman",
                            LastName = "Kaya",
                            Phone = "05538275858",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Entities.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageOptionId")
                        .HasColumnType("int");

                    b.Property<int>("PhotographerId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PackageOptionId");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Project.Entities.Models.ReservationExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtraServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtraServiceId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationExtras");
                });

            modelBuilder.Entity("Project.Entities.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumCompanyId");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumCompanyId = 1,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3677),
                            Name = "New Line Collection",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AlbumCompanyId = 1,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3677),
                            Name = "Standart Seri",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AlbumCompanyId = 1,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3677),
                            Name = "Kampanya Seri",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AlbumCompanyId = 1,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3677),
                            Name = "Çizgi Avantaj Seri",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Entities.Models.SizeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("SizeOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x70 New Line",
                            ServiceCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x60 New Line",
                            ServiceCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x80 New Line",
                            ServiceCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x70 Standart",
                            ServiceCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x50 Standart",
                            ServiceCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x60 Standart",
                            ServiceCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x60 Standart",
                            ServiceCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x80 Standart",
                            ServiceCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x60 Kampanya",
                            ServiceCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x50 Kampanya",
                            ServiceCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x70 Kampanya",
                            ServiceCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x50 Kampanya",
                            ServiceCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x60 Kampanya",
                            ServiceCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x76 Kampanya",
                            ServiceCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x80 Kampanya",
                            ServiceCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x70 Çizgi Avantaj",
                            ServiceCategoryId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x60 Çizgi Avantaj",
                            ServiceCategoryId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x70 Çizgi Avantaj",
                            ServiceCategoryId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x50 Çizgi Avantaj",
                            ServiceCategoryId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "25x60 Çizgi Avantaj",
                            ServiceCategoryId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2025, 5, 16, 17, 7, 17, 498, DateTimeKind.Local).AddTicks(3697),
                            Dimension = "30x50 Çizgi Avantaj",
                            ServiceCategoryId = 4,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.Entities.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.Entities.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Entities.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.Entities.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Entities.Models.ExtraService", b =>
                {
                    b.HasOne("Project.Entities.Models.ExtraServiceCategory", "ExtraServiceCategory")
                        .WithMany("ExtraServices")
                        .HasForeignKey("ExtraServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraServiceCategory");
                });

            modelBuilder.Entity("Project.Entities.Models.Payment", b =>
                {
                    b.HasOne("Project.Entities.Models.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Project.Entities.Models.Reservation", b =>
                {
                    b.HasOne("Project.Entities.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Entities.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Entities.Models.Location", "Location")
                        .WithMany("Reservations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Entities.Models.PackageOption", "PackageOption")
                        .WithMany("Reservations")
                        .HasForeignKey("PackageOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Entities.Models.Photographer", "Photographer")
                        .WithMany("Reservations")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Entities.Models.ServiceCategory", "ServiceCategory")
                        .WithMany("Reservations")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Customer");

                    b.Navigation("Location");

                    b.Navigation("PackageOption");

                    b.Navigation("Photographer");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("Project.Entities.Models.ReservationExtra", b =>
                {
                    b.HasOne("Project.Entities.Models.ExtraService", "ExtraService")
                        .WithMany()
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Entities.Models.Reservation", "Reservation")
                        .WithMany("ReservationExtras")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraService");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Project.Entities.Models.ServiceCategory", b =>
                {
                    b.HasOne("Project.Entities.Models.AlbumCompany", "AlbumCompany")
                        .WithMany("ServiceCategories")
                        .HasForeignKey("AlbumCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumCompany");
                });

            modelBuilder.Entity("Project.Entities.Models.SizeOption", b =>
                {
                    b.HasOne("Project.Entities.Models.ServiceCategory", "ServiceCategory")
                        .WithMany("SizeOptions")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("Project.Entities.Models.AlbumCompany", b =>
                {
                    b.Navigation("ServiceCategories");
                });

            modelBuilder.Entity("Project.Entities.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Project.Entities.Models.ExtraServiceCategory", b =>
                {
                    b.Navigation("ExtraServices");
                });

            modelBuilder.Entity("Project.Entities.Models.Location", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Project.Entities.Models.PackageOption", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Project.Entities.Models.Photographer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Project.Entities.Models.Reservation", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ReservationExtras");
                });

            modelBuilder.Entity("Project.Entities.Models.ServiceCategory", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("SizeOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
